
export interface ExerciseDatabase {
  [key: string]: string[];
}

export const GEMINI_MODEL = "gemini-3.5-flash"; 
export const GEMINI_PRO_MODEL = "gemini-3.1-pro-preview";
export const GEMINI_FLASH_LITE_MODEL = "gemini-3.1-flash-lite";
export const IMAGEN_MODEL = "gemini-2.5-flash-image"; // For image generation logic
export const SERIES_OPTIONS = ["A", "B", "C", "D", "E"];

export const EXERCISE_CATALOG: Record<string, string[]> = {
  "PEITORAL": [
    "SUPINO ABERTO COM HALTER", 
    "SUPINO ABERTO NO SMITH", 
    "SUPINO VERTICAL NA MÁQUINA",
    "SUPINO ABERTO NO BANCO RETO COM HALTER",
    "SUPINO ABERTO ALTERNADO NO BANCO 30 GRAUS COM HALTER",
    "CRUCIFIXO ABERTO NO BANCO RETO COM HALTER",
    "CRUCIFIXO ABERTO ALTERNADO NO BANCO 30 GRAUS NO CROSS",
    "CRUCIFIXO NO VOADOR PEITORAL",
    "VOADOR PEITORAL",
    "PULL UP NO CROSS", 
    "EXTENSÃO DE COTOVELOS NO SOLO"
  ],
  "OMBROS": [
    "DESENVOLVIMENTO NO SMITH",
    "DESENVOLVIMENTO NO BANCO 75 GRAUS COM HALTER",
    "DESENVOLVIMENTO ARNOLD EM PÉ", 
    "ELEVAÇÃO LATERAL COM HALTER",
    "ELEVAÇÃO FRONTAL COM HALTER",
    "ABDUÇÃO DE OMBROS EM PÉ COM HALTER", 
    "ABDUÇÃO DE OMBROS ALTERNADO EM PÉ", 
    "FLEXÃO DE OMBRO ALTERNADO NO BANCO 75 GRAUS COM HALTER",
    "REMADA ALTA EM PÉ NO CROSS", 
    "ROTAÇÃO EXTERNA DE OMBRO NO CROSS", 
    "ENCOLHIMENTO DE OMBROS NO CROSS",
    "CRUCIFIXO INVERSO NO BANCO 30 GRAUS COM HALTER"
  ],
  "DORSAIS": [
    "PUXADA ABERTA NO PULLEY ALTO COM BARRA RETA",
    "PUXADA SUPINADA NO PULLEY ALTO",
    "PUXADA NEUTRA NO PULLEY", 
    "PUXADA ABERTA NA BARRA FIXA",
    "REMADA ABERTA EM PÉ NO CROSS",
    "REMADA NEUTRA NA MÁQUINA SENTADA",
    "REMADA CURVADA COM HALTER", 
    "REMADA CAVALO NA MÁQUINA",
    "EXTENSÃO DE OMBROS EM PÉ NO CROSS",
    "ADUÇÃO DE OMBROS NO CROSS", 
    "PULL OVER COM HALTER"
  ],
  "TRÍCEPS": [
    "TRÍCEPS EM PÉ NO CROSS COM BARRA RETA",
    "TRÍCEPS COICE NO CROSS", 
    "TRÍCEPS FRANCÊS NO BANCO 75 GRAUS", 
    "TRÍCEPS TESTA COM BARRA H", 
    "TRÍCEPS NA PARALELA", 
    "TRÍCEPS SUPERMAN NO CROSS",
    "SUPINO FECHADO NO BANCO RETO"
  ],
  "BÍCEPS": [
    "BÍCEPS EM PÉ NO CROSS COM BARRA RETA",
    "BÍCEPS ALTERNADO NO BANCO 60 GRAUS", 
    "BÍCEPS SCOTT NA MÁQUINA", 
    "BÍCEPS CONCENTRADO", 
    "BÍCEPS EM PÉ COM BARRA W", 
    "BÍCEPS NO CROSS COM CORDA"
  ],
  "QUADRÍCEPS": [
    "AGACHAMENTO LIVRE COM HALTER",
    "AGACHAMENTO LIVRE", 
    "AGACHAMENTO NO SMITH", 
    "LEG PRESS 45 GRAUS", 
    "LEG PRESS 90 GRAUS", 
    "LEG PRESS HORIZONTAL",
    "LEG PRESS HORIZONTAL (AMPLITUDE REDUZIDA)",
    "LEG PRESS HORIZONTAL UNILATERAL",
    "CADEIRA EXTENSORA", 
    "AGACHAMENTO NO BANCO COM HALTER",
    "AGACHAMENTO PASSADA", 
    "AGACHAMENTO NO SISSY"
  ],
  "ADUTORES": [
    "ADUÇÃO DE QUADRIL NO CROSS", 
    "CADEIRA ADUTORA", 
    "ADUÇÃO COM CANELEIRA", 
    "AGACHAMENTO SUMÔ COM ROTAÇÃO EXTERNA"
  ],
  "GLÚTEOS": [
    "AGACHAMENTO SUMÔ COM HALTER", 
    "ELEVAÇÃO DE QUADRIL NO SOLO",
    "ELEVAÇÃO DE QUADRIL NO BANCO (HIP THRUST)",
    "ELEVAÇÃO DE QUADRIL NO SMITH", 
    "EXTENSÃO DE QUADRIL EM PÉ COM CANELEIRA",
    "ABDUÇÃO DE QUADRIL EM PÉ COM CANELEIRA",
    "LEVANTAMENTO TERRA NO CROSS", 
    "LEVANTAMENTO TERRA COM HALTER",
    "STIFF EM PÉ COM HALTER", 
    "CADEIRA ABDUTORA", 
    "EXTENSÃO DE QUADRIL NO GRAVITON"
  ],
  "POSTERIORES DE COXA": [
    "CADEIRA FLEXORA", 
    "FLEXÃO DE JOELHO NÓRDICA", 
    "MESA FLEXORA", 
    "STIFF UNILATERAL", 
    "STIFF UNILATERAL COM HALTER",
    "FLEXÃO DE JOELHO NA BOLA"
  ],
  "PANTURRILHA": [
    "FLEXÃO PLANTAR NO LEG PRESS", 
    "FLEXÃO PLANTAR EM PÉ", 
    "FLEXÃO PLANTAR NO SMITH", 
    "PANTURRILHA EM PÉ NO SMITH",
    "FLEXÃO PLANTAR NO DEGRAU"
  ],
  "PARAVERTEBRAIS": [
    "ELEVAÇÃO DE QUADRIL NO SOLO", 
    "EXTENSÃO DE TRONCO NO APARELHO", 
    "PERDIGUEIRO NO SOLO", 
    "MATA-BORRÃO"
  ],
  "ABDOMINAIS": [
    "ABDOMINAL CRUNCH MÁQUINA", 
    "ABDOMINAL INFRA PENDURADO", 
    "PRANCHA VENTRAL", 
    "ABDOMINAL SUPRA NA BOLA",
    "ABDOMINAL SUPRA NO SOLO"
  ]
};

export const FULL_EXERCISE_LIST = Object.entries(EXERCISE_CATALOG).flatMap(([group, items]) => 
  items.map(name => ({ group, name }))
);
